#! /usr/bin/env php

<?php

use Pepeloper\CsvParser\Csv;
use Pepeloper\TemplateParser\Template;
use Goutte\Client;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$template = new Template();

$app = new Application('Pepeloper', '1.0');

$csv = new Csv();
$app->add(new Pepeloper\Redirections($template, $csv));

$client = new Client();
$app->add(new Pepeloper\LaDrupalera($template, $client));

$app->run();
