#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Pepeloper\TemplateParser\Template;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$template = new Template();

$app = new Application('Pepeloper', '1.0');

$app->add(new Pepeloper\Redirections($template));

$app->run();
